### ISSUE TITLE
'Razorpay/Razorpay-Swift.h' file not found

### ISSUE THREAD

**Issue by karthikmandava7** [razorpay/react-native-razorpay#242]
![Screen Shot 2019-12-27 at 11 39 26 AM](https://user-images.githubusercontent.com/23091328/71504007-9ac80e00-289d-11ea-82de-37c71ce848bc.png)
I'm trying to integrate React Native SDK for Custom UI, but it's not working as expected. Maybe I've done wrong in any place in the integration process, but I'm unable to find out exactly the issue. Can you please help.
Xcode - Version 11.2.1 (11B53)
 "react": "16.9.0"
"react-native": "^0.60.0"

**Comment by Nautiyalsachin** [comment]
Hi @karthikmandava7. We have released an upgraded version (i.e. 2.1.2). Can you please update and let me know your response.

**Comment by prataprish007** [comment]
i am getting same error in current version

**Comment by Nautiyalsachin** [comment]
Are you following these steps - https://github.com/razorpay/react-native-razorpay/wiki#installation-steps. ?

**Comment by Nautiyalsachin** [comment]
Closing this due to inactivity. You can always open the issue again.

**Comment by karanwadhwa** [comment]
I too am getting this issue in the latest version - 2.2.4 after upgrading from 2.1.23
```
node_modules/react-native-razorpay/ios/RazorpayCheckout.m:12:9: 'Razorpay/Razorpay-Swift.h' file not found
```
I manually linked it (without cocoapods) as instructed [here](https://github.com/razorpay/react-native-razorpay#manual)

the only thing I did differently was that I also added the following to Header Search Paths
`${SRCROOT}/../../../ios/Pods/Headers/Public`
because without it, my build kept failing with this error
```
RazorpayCheckout.h:9:9: fatal error: 'RCTBridgeModule.h' file not found
```

**Comment by Nautiyalsachin** [comment]
Hi @karanwadhwa, the Razorpay SDK inside our react native plugin is getting downloaded from cocoa pods and it has a pod dependency. 

I would suggest you to use pod as it is recommended by us and by react-native latest versions. Currently our cocoapod plugin version is  1.1.12. 

You can check the current pod versions inside podfile.lock. If it's not the latest then please update it.

If you still want to go without the pod then you have to add the latest razorpay SDK in your codebase, that you can download the latest SDK from [here](https://razorpay.com/docs/payment-gateway/ios-integration/standard/) and try adding that into your project.

**Comment by PulkitAsri** [comment]
react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found

**Comment by PulkitAsri** [comment]
`node_modules/react-native-razorpay/ios/RazorpayCheckout.m:12:9: 'Razorpay/Razorpay-Swift.h' file not found`
 @Nautiyalsachin  I too  am getting the same error, *mentioned above, 
I have already tried doing it with and without CocoaPods,
But the build is still failing.
Not sure what to do, any suggestions?


Versions->

react  => 16.13.1 
react-native => 0.63.3 
react-native-razorpay => ^2.2.8,
CocoaPods =>1.11.2 
Platforms => iOS 14.5, 
Xcode => 12.5.1/12E507

**Comment by ramprasadAnand** [comment]
@tabin-accessai i would suggest to remove the Podfile.lock, Runner.xcworkspace, and Pods from your project's ios folder and run pod install. Do let us know if the error is still not resolved.

**Comment by tabin-accessai** [comment]
> @tabin-accessai i would suggest to remove the Podfile.lock, Runner.xcworkspace, and Pods from your project's ios folder and run pod install. Do let us know if the error is still not resolved.

Thanks for replying, but the error still persists.
